### PR TITLE
Add devise

### PR DESCRIPTION
**Pull request by najibullahjafari**
Here we did the following requirments:
We removed current_user method in ApplicationController, devise will provide us with one.
A user can register.
A user logs in with a combination of email and password.
Hashed password is stored in the database.
A user can ask for confirmation of email.
A user can reset password.

### CODE REVIEW

**Review by Gambit142 — COMMENTED** [review]
Hi @najibullahjafari 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- I can see that this is a second or third review request, kindly provide the link to the pull request where previous reviewers suggested changes. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by najibullahjafari** [comment]
@Gambit142 

That is why  I saw approval in my dashboard when my teammate sent the pull request, so I submitted my project.
Then I merged the branch, and after that, a  CR reverted my dashboard so because of that I made the pull request again!


you can see the case here: https://github.com/cancelei/blog-in-rails/pull/9#issuecomment-1773206554


Screenshot 2023-10-20 215258

Screenshot 2023-10-21 000543

**Review by Lucas-Masaba — CHANGES_REQUESTED** [review]
# Hello @najibullahjafari  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Good communication with the code reviewer :microphone: 
- Devise is working as expected :gear: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] In your `User model`, you have two devise blocks and yet you should only have one. Please remove the 1st one.
```diff
- devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
```

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Reem-lab — APPROVED** [review]
# Hi  Team,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on setting up devise 🤩
- [ ]  No Linters error ✅
- [ ] Good job working on the requested changes ✨


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
